#!/usr/bin/env python3

"""
Test script to verify footer generation with business_info
"""

import sys
import os
sys.path.append(os.path.dirname(__file__))

from workflows.workflow import WebsiteGenerationWorkflow

def test_footer_with_business_info():
    print("Testing footer generation with business_info...")
    
    # Create workflow instance
    workflow = WebsiteGenerationWorkflow()
    
    # Sample business info from user form
    business_info = {
        'business_name': 'Green Gardens Landscaping',
        'business_category': 'landscaping',
        'business_description': 'Professional landscaping and garden design services in Denver, Colorado.',
        'location': 'Denver, Colorado',
        'target_audience': 'Homeowners and businesses in Denver area'
    }
    
    # Sample content data (minimal for footer test)
    content_data = {
        'footer_company_description': 'Creating beautiful outdoor spaces since 2015.',
        'footer_contact_info': {
            'phone': '(303) 555-LAWN',
            'email': 'info@greengardens.com',
            'hours': 'Mon-Sat 8AM-6PM'
        },
        'footer_services': ['Landscape Design', 'Lawn Care', 'Tree Service', 'Irrigation'],
        'footer_areas': ['Denver', 'Boulder', 'Aurora', 'Lakewood'],
        'footer_social_links': {
            'facebook': 'https://facebook.com/greengardens',
            'instagram': '@greengardens_co'
        }
    }
    
    print(f"Business Name: {business_info['business_name']}")
    print(f"Category: {business_info['business_category']}")
    print(f"Location: {business_info['location']}")
    print()
    
    # Generate footer
    footer_html = workflow._generate_footer_content(content_data, business_info)
    
    print("=" * 60)
    print("GENERATED FOOTER HTML:")
    print("=" * 60)
    print(footer_html)
    
    # Test with minimal business info (like what user might provide)
    print("\n" + "=" * 60)
    print("TESTING WITH MINIMAL BUSINESS INFO:")
    print("=" * 60)
    
    minimal_business_info = {
        'business_name': 'Quick Fix Auto Repair',
        'business_category': 'automotive',
        'business_description': 'Fast and reliable auto repair services.',
        'location': 'Phoenix, AZ'
    }
    
    minimal_content_data = {}  # No footer content generated by AI
    
    footer_html_minimal = workflow._generate_footer_content(minimal_content_data, minimal_business_info)
    print(footer_html_minimal)
    
    # Save test output
    with open('test_footer_business_info_output.html', 'w', encoding='utf-8') as f:
        f.write(f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Footer Test with Business Info</title>
    <style>
        .footer {{
            background-color: #333;
            color: white;
            padding: 3rem 0 1rem;
        }}
        .footer-content {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 2rem;
            margin-bottom: 2rem;
        }}
        .footer-section h3 {{
            color: #fff;
            margin-bottom: 1rem;
            font-size: 1.2rem;
        }}
        .footer-section ul {{
            list-style: none;
            padding: 0;
        }}
        .footer-section ul li {{
            margin-bottom: 0.5rem;
        }}
        .footer-section ul li a {{
            color: #ccc;
            text-decoration: none;
        }}
        .footer-section ul li a:hover {{
            color: #fff;
        }}
        .footer-section p {{
            color: #ccc;
            line-height: 1.6;
        }}
        .footer-section p strong {{
            color: #fff;
        }}
        .social-links {{
            margin-top: 1rem;
        }}
        .social-links a {{
            margin-right: 1rem;
            text-decoration: none;
        }}
        .footer-bottom {{
            border-top: 1px solid #555;
            padding-top: 1rem;
            text-align: center;
            color: #ccc;
        }}
        .container {{
            max-width: 1200px;
            margin: 0 auto;
            padding: 0 1rem;
        }}
        body {{
            font-family: Arial, sans-serif;
            margin: 0;
            background-color: #f5f5f5;
        }}
        .demo-section {{
            padding: 2rem;
            background: white;
            margin-bottom: 2rem;
        }}
    </style>
</head>
<body>
    <div class="demo-section">
        <h1>Footer Test with Business Info</h1>
        <h2>1. Complete Footer (with AI-generated content)</h2>
        <p><strong>Business:</strong> {minimal_business_info['business_name']}</p>
        <p><strong>Category:</strong> {minimal_business_info['business_category']}</p>
        <p><strong>Location:</strong> {minimal_business_info['location']}</p>
    </div>
    
    {footer_html}
    
    <div class="demo-section">
        <h2>2. Minimal Footer (business info only)</h2>
        <p><strong>Business:</strong> {minimal_business_info['business_name']}</p>
        <p><strong>Category:</strong> {minimal_business_info['business_category']}</p>
        <p><strong>Location:</strong> {minimal_business_info['location']}</p>
    </div>
    
    {footer_html_minimal}
</body>
</html>
        """)
    
    print(f"\n✅ Footer test saved to 'test_footer_business_info_output.html'")

if __name__ == "__main__":
    test_footer_with_business_info()
